INHERIT: ./common/mkdocs_base.yml

site_name: ポートフォリオ
# site_description: sasano8's portfolio
site_url: https://portfolio.ys-method.com/print_page/
# repo_name: encode/httpx
repo_url: https://portfolio.ys-method.com/print_page/
edit_uri: "edit/main/docs/"

nav:
  - はじめに: "index.md"
  - 職務経歴: "background.md"
  - 技術スタック: "tech_stack.md"
